version: "3"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ngcashdatabase
      POSTGRES_USER: userformpostgresdatabase
      POSTGRES_PASSWORD: mustbestrongapassword
    ports:
      - 5432:5432
    