version: "3"

services:
  ngbackend:
    depends_on:
      - database
    build: .
    command:  bash -c "npm run migrate && npm run dev"
    
    container_name: ngbackend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - network

  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ngcashdatabase
      POSTGRES_USER: userformpostgresdatabase
      POSTGRES_PASSWORD: mustbestrongapassword
    ports:
      - 5432:5432
    networks:
      - network


networks:
  network:
    driver: bridge
    